odevzdani ukolu
ladaedu/oci-terraform-intro pull request #6
Opened 2020-05-20 16:06 UTC by JanVykruta

Upravil jsem terraform soubory aby se infrastruktura dala nahodit. Dale jsem pridal par testu. Napriklad test jestli LB pouziva round robin, nebo jake Shape pouzivaji Bastion instance. Pokud by jich bylo malo, tak muzu jeste nejake pridat. Zaroven jsem narazil na problem, a to jest, ze se z Bastion nejde pripojit na vypocetni instance, tedy testy `sshWeb` a `netstatNginx` neprochazeji s chybou: `ssh: rejected: administratively prohibited (open failed)`. Nevim jestli mam nekde najakou botu v konfiguraci siti nebo je ssh ve vypocetnich instancich spatne nastavene. Dekuji za cviceni, prestoze jsem byl aktivne jen na jednom, zhlednul jsem si ostatni ze zaznamu.

2020-05-25 14:06 UTC, sw-samuraj requested changes
Aktuálně, změny v pull requestu vytvoří pouze:

- VCN
- Internet Gateway
- NAT Gateway

```
$ tf plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

oci_core_virtual_network.VCN: Refreshing state... [id=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaasfuycaqacnoxeoecqakr3c23pfwnipcwvxaytvxwuac57xrnxwsq]
oci_core_nat_gateway.NATGateway: Refreshing state... [id=ocid1.natgateway.oc1.eu-frankfurt-1.aaaaaaaag46fjmemscvg3wkwovop6evntoelfvofn6orpvnpfvm7t5gfbsza]
oci_core_internet_gateway.InetGW: Refreshing state... [id=ocid1.internetgateway.oc1.eu-frankfurt-1.aaaaaaaasaxndfvgt5qr3yvwhskdg65643cm72d3bci57atrnumvzmh25xqq]

------------------------------------------------------------------------

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
```

2020-05-25 15:13 UTC, sw-samuraj commented
Po přejmenování všech `*.tfx` souborů na `*.tf` hlásí _Terraform_ chybu:

```
$ tf plan

Error: Reference to undeclared resource

  on bastion-network.tf line 37, in resource "oci_core_subnet" "BastionSubnet":
  37:   availability_domain = data.oci_identity_availability_domains.ADs.availability_domains[count.index]["name"]

A data resource "oci_identity_availability_domains" "ADs" has not been
declared in the root module.
```

2020-05-25 15:35 UTC, sw-samuraj commented
_Terratest_ testy jsou v pořádku. :heavy_check_mark:

2020-05-25 15:38 UTC, sw-samuraj commented
@JanVykruta Přejmenujte, prosím, všechny `*.tfx` soubory, např.:
```
git mv bastion.tf3 bastion.tf
```
a udělejte `commit`/`push`.

2020-05-26 18:33 UTC, JanVykruta commented
@sw-samuraj Prejmenoval jsem `.tfx` na `.tf` a `push`nul.

2020-05-27 11:47 UTC, sw-samuraj approved these changes
Well done! :+1:

2021-05-12 18:47 UTC, closed without merging